import {
  CDN_URL,
  CLIENT_NAME,
  CONTACT_ADDRESS,
  CONTACT_PHONE_NUMBER,
  GOOGLE_MAPS_LOCATION,
  POINT_OF_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
} from "./config";

export {
  CDN_URL,
  CLIENT_NAME,
  CONTACT_ADDRESS,
  CONTACT_PHONE_NUMBER,
  GOOGLE_MAPS_LOCATION,
  POINT_OF_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
};
