import {
  CDN_URL,
  CONTACT_ADDRESS,
  CONTACT_PHONE_NUMBER,
  GOOGLE_MAPS_LOCATION,
  POINT_OF_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL
} from "./config";

import { SERVICES_API_KEY } from "./secrets";

export {
  CDN_URL,
  CONTACT_ADDRESS,
  CONTACT_PHONE_NUMBER,
  GOOGLE_MAPS_LOCATION,
  POINT_OF_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
  SERVICES_API_KEY
};
